const products = [
  {
    img: "https://www.innersloth.com/wp-content/uploads/2023/12/out_on_holiday_FINAL_2023-257x154.png",
    category: "among-us",
    date: "December 24, 2023",
    heading: "🎄 New Year presents",
    info: "This New Year, Among Us players can expect a delightful  array of festive skins to spruce up their Crewmates.  Dive into the holiday spirit by donning  the iconic red suit and hat to transform into a cheerful Santa, ready to spread joy across the spacecraft.",
  },
  {
    img: "https://img.championat.com/s/735x490/news/big/i/i/najden-sposob-kak-igrat-v-brawl-stars-iz-rossii-bez-vpn_16824440711888973803.jpg",
    category: "brawl-stars",
    date: "November 2, 2023",
    heading: "🥇 Team Up for Intense Battles",
    info: "Experience synergy like never before with the arrival of Dynamic Duo Mode in Brawl Stars. Form powerful pairs, strategize with your partner, and dominate the arena with coordinated attacks.",
  },
  {
    img: "https://img.tapimg.net/market/images/54afda87e3214bbec1f77401cd109d83.jpg?imageView2/2/w/1080/h/1080/q/80/format/jpg/interlace/1/ignore-error/1",
    category: "dig-2-china",
    date: "April 5, 2024",
    heading: "🎊 Treasure Caverns",
    info: "Delve into newly discovered caverns, each with its unique set of puzzles, traps, and treasures. Navigate through intricate mazes and use your wit to overcome obstacles.",
  },
  {
    img: "https://www.gematsu.com/wp-content/uploads/2023/09/Among-Us-Map_09-14-23.jpg",
    category: "among-us",
    date: "February 14, 2024",
    heading: "🗺️ New Maps Await Crewmates!",
    info: "Embark on thrilling journeys across fresh landscapes as Among Us unveils a series of new maps, promising exciting tasks, devious impostors, and uncharted territories for crewmates to navigate.",
  },
  {
    img: "https://clan.cloudflare.steamstatic.com/images/33836086/12c05226388297f8cc415a0fef9f14a280e6f3da.png",
    category: "among-us",
    date: "January 23, 2024",
    heading: "📍 New Achievements Unlocked",
    info: "Sharpen your skills and embrace new challenges with the introduction of achievements in Among Us. From masterful deception to completing tasks at warp speed, there's an achievement for every Crewmate.",
  },
  {
    img: "https://static1-br.millenium.gg/articles/5/13/76/5/@/150879-buzz-article_cover_bd-1.jpg",
    category: "brawl-stars",
    date: "January 12, 2024",
    heading: "👻Unleash Chaos with the Mysterious Maverick",
    info: "Meet the newest addition to the Brawl Stars roster – Maverick! This mysterious Brawler brings a set of unpredictable abilities to the arena, changing the dynamics of every match.",
  },
  {
    img: "https://www.innersloth.com/wp-content/uploads/2021/06/screenshot-img14@2x.png",
    category: "dig-2-china",
    date: "February 24, 2024",
    heading: "⛑️New Factions Rise in Underground Wars",
    info: "The underground world of Dig 2 China is about to witness a seismic shift as new factions rise to power. Engage in underground wars, align with powerful allies, and conquer the depths.",
  },
  {
    img: "https://www.innersloth.com/wp-content/uploads/2023/12/out_on_holiday_FINAL_2023-257x154.png",
    category: "dig-2-china",
    date: "February 22, 2024",
    heading: "🛠️Forge Your Ultimate Tools",
    info: "Crafting gets a major overhaul in Dig 2 China's latest update. Master the art of forging as you create powerful tools, uncover rare materials, and customize your digging experience like never before.",
  },
  {
    img: "https://brawlstars.b-cdn.net/wp-content/uploads/2022/05/ocellus-services-02-ruffstarpower-details-copy.jpg",
    category: "brawl-stars",
    date: "March 17 , 2024",
    heading: "🐉 Forge Your Legacy in the Competitive Scene",
    info: "Dive into the world of competitive gaming as Brawl Stars officially embraces eSports. Join tournaments, climb the ranks, and etch your name in Brawl Stars history as a formidable Brawler.",
  },
  {
    img: "https://i.ytimg.com/vi/U16b-uHtBiw/maxresdefault.jpg",
    category: "innersloth",
    date: "January 20, 2024",
    heading: "🥳Cheers to Another Year",
    info: "Innersloth, the creative force behind gaming sensations like Among Us and The Henry Stickmin Collection, recently marked another milestone with a joyous celebration of its birthday. The gaming community joined in the festivities, making it a day to remember for fans worldwide.",
  },
  {
    img: "https://img.artpal.com/872122/1-21-7-13-1-52-24m.jpg",
    category: "innersloth",
    date: "March 9, 2024",
    heading: "❤️ Cross-Platform Integration",
    info: "Innersloth aims to break down barriers by enhancing cross-platform compatibility. Soon, players will seamlessly connect with friends regardless of their gaming platform, fostering a more inclusive and interconnected gaming experience.",
  },
  {
    img: "https://www.lavanguardia.com/andro4all/hero/2020/11/Dig2China.jpg?width=1200",
    category: "dig-2-china",
    date: "April 29, 2024",
    heading: "🌟Unearths Mythical Realms in Latest Expansion",
    info: "Embark on a journey beyond the surface as Dig 2 China unveils a mystical expansion. Delve into mythical realms, uncover ancient treasures, and face new challenges that redefine the art of digging.",
  },
  {
    img: "https://app.yipee.cc/wp-content/uploads/2021/05/0581b9d1cae0764189d9f6247103d5dd.jpg",
    category: "among-us",
    date: "May 30, 2024",
    heading: "🔥Limited-Time Cosmetics and Festivities Await!",
    info: "Step right up to the Brawl Stars Carnival! Enjoy limited-time cosmetics, festive decorations, and mini-games that add a touch of carnival magic to the Brawl Stars universe.",
  },
  {
    img: "https://mir-s3-cdn-cf.behance.net/project_modules/1400/9c3e19160503601.63b594b84d006.jpg",
    category: "fan-art",
    date: "December 31, 2023",
    heading: "🎨 Celebrating Creativity Across Fandoms",
    info: "Dive into the mesmerizing world of fan art as artists from various fandoms showcase their talents. From stunning digital illustrations to handcrafted masterpieces, the Fan Art Extravaganza is a celebration of creativity.",
  },
];
